### ISSUE TITLE
Sorting demands on backend

### ISSUE THREAD

**Issue by michaldomagalski** [copotrzebne-pl/copotrzebne-api#143]
https://github.com/copotrzebne-pl/copotrzebne-frontend/issues/157

We need to sort demands on backend. We should add query param for ways of sorting.

**Comment by jakubgwozdz** [comment]
I understand that right now the frontend merges two lists, 
supplies from system-wide [`/supplies`](https://github.com/copotrzebne-pl/copotrzebne-api/blob/15714c3bba415cf836cc420d466354e5f6205216/src/supplies/supplies.controller.ts#L55) endpoint and 
demands from place-specific [`/places/:id/demands`](https://github.com/copotrzebne-pl/copotrzebne-api/blob/2739d19edf6e2884161e072acdd4faa90c603d4b/src/places/controllers/places.controller.ts#L125) endpoint

The idea would be to prepare third endpoint, place-specific supplies, e.g. [`/places/:id/demands`] that merges these lists in backend and places items that are already on demands list on the beginning (preferably ordered by demanded date?)

would that provide expected result, @michaldomagalski @Kamil-96?

**Comment by michaldomagalski** [comment]
@jakubgwozdz not exactly. We should handle additional query param to `/places/:id/demands` which triggers sorting demanda by `createdAt` in descending order instead of sorting the by supplies name and prio. That thing alone should be sufficient enough for frontend client.
