### ISSUE TITLE
Add new "admin" or "moderator" role and account for students to be able to access mutliple organisations in app

### ISSUE THREAD

**Issue by agnieszkalasyk** [copotrzebne-pl/copotrzebne-api#160]
We should have a separate role and a new account with limited admin privileges that would be used by students to acces and change multiple organisations'a data and needs.
This account should have:
- all organisations available
- possibility to add/change the org data and needs
- possibility to add org announcements
(similar role to multiuser but for all of the organisations within our database)

it should not be possible though to use this account to:
- delete organisation
- moderate - add new organisation
- create new users
- add new organisation

**Comment by agnieszkalasyk** [comment]
@michaldomagalski @baqui what do you think? shall we scope the role differently giving it more privileges?

**Comment by michaldomagalski** [comment]
I am thinking maybe to allow adding new organization too (but not deleting)?

**Comment by agnieszkalasyk** [comment]
yeah, I was thinking about it too, let's add it :)

**Comment by michaldomagalski** [comment]
Alright, so I've added a new role `moderator`.

User with this role:
- **Can** add and update `places`, but **cannot** delete them
- **Can** create, update and delete `demands`
- **Can** add and update `internal` and `public announcements` but **cannot** delete them
- **Can** add and update `internal announcements` `comments` but **cannot** delete them

**Comment by michaldomagalski** [comment]
I am not quite convinced about two last points in my previous comment though. Maybe moderators should have the ability to do delete `announcements` and `comments` too? 🤔 @agnieszkalasyk @baqui , what do you think?

**Comment by agnieszkalasyk** [comment]
I was thinking exactly the same
